# Form implementation generated from reading ui file 'd:\Python_Workspace\UI\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_login(object):
    def setupUi(self, Dialog_login):
        Dialog_login.setObjectName("Dialog_login")
        Dialog_login.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_login.sizePolicy().hasHeightForWidth())
        Dialog_login.setSizePolicy(sizePolicy)
        Dialog_login.setMinimumSize(QtCore.QSize(400, 300))
        Dialog_login.setMaximumSize(QtCore.QSize(4000, 300))
        self.label = QtWidgets.QLabel(parent=Dialog_login)
        self.label.setGeometry(QtCore.QRect(70, 50, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_login = QtWidgets.QPushButton(parent=Dialog_login)
        self.pushButton_login.setGeometry(QtCore.QRect(140, 230, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog_login)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 150, 174, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Username = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.horizontalLayout_2.addWidget(self.lineEdit_Username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_login)

    def retranslateUi(self, Dialog_login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_login.setWindowTitle(_translate("Dialog_login", "登录-局域网聊天"))
        self.label.setText(_translate("Dialog_login", "登录-局域网聊天"))
        self.pushButton_login.setText(_translate("Dialog_login", "登录"))
        self.label_2.setText(_translate("Dialog_login", "账号"))
        self.lineEdit_Username.setPlaceholderText(_translate("Dialog_login", "用户名"))
        self.label_3.setText(_translate("Dialog_login", "密码"))
        self.lineEdit_password.setPlaceholderText(_translate("Dialog_login", "密码"))
