# Form implementation generated from reading ui file 'd:\Python_Workspace\Client\privatechat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PrivateChat(object):
    def setupUi(self, PrivateChat):
        PrivateChat.setObjectName("PrivateChat")
        PrivateChat.resize(810, 656)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(PrivateChat)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_chatdispaly = QtWidgets.QLabel(parent=PrivateChat)
        self.label_chatdispaly.setMaximumSize(QtCore.QSize(80, 20))
        self.label_chatdispaly.setObjectName("label_chatdispaly")
        self.horizontalLayout_2.addWidget(self.label_chatdispaly)
        self.label_chatobject = QtWidgets.QLabel(parent=PrivateChat)
        self.label_chatobject.setMaximumSize(QtCore.QSize(80, 20))
        self.label_chatobject.setObjectName("label_chatobject")
        self.horizontalLayout_2.addWidget(self.label_chatobject)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser_message = QtWidgets.QTextBrowser(parent=PrivateChat)
        self.textBrowser_message.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_message.setObjectName("textBrowser_message")
        self.verticalLayout.addWidget(self.textBrowser_message)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=PrivateChat)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.listView = QtWidgets.QListView(parent=PrivateChat)
        self.listView.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=PrivateChat)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_refresh = QtWidgets.QPushButton(parent=PrivateChat)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout_2.addWidget(self.pushButton_refresh)
        self.pushButton_send = QtWidgets.QPushButton(parent=PrivateChat)
        self.pushButton_send.setObjectName("pushButton_send")
        self.verticalLayout_2.addWidget(self.pushButton_send)
        self.pushButton_exit = QtWidgets.QPushButton(parent=PrivateChat)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout_2.addWidget(self.pushButton_exit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(PrivateChat)
        QtCore.QMetaObject.connectSlotsByName(PrivateChat)

    def retranslateUi(self, PrivateChat):
        _translate = QtCore.QCoreApplication.translate
        PrivateChat.setWindowTitle(_translate("PrivateChat", "私聊-局域网聊天"))
        self.label_chatdispaly.setText(_translate("PrivateChat", "聊天对象："))
        self.label_chatobject.setText(_translate("PrivateChat", "1"))
        self.label.setText(_translate("PrivateChat", "发送文件"))
        self.pushButton_refresh.setText(_translate("PrivateChat", "刷新消息"))
        self.pushButton_send.setText(_translate("PrivateChat", "发送"))
        self.pushButton_exit.setText(_translate("PrivateChat", "退出"))
